const productos = [{
    id: 1,
    nombre: "Victoria's Secret (Algodón)",
    foto: "./img/vs.jpeg",
    descripcion: "Docena de less VS de algodón, con elastico afelpado de 30mm. La docena viene surtida en 3 colores, negro, blanco y gris (4 unidades de cada color).",
    precio: 5600,
},
{
    id: 2,
    nombre: "Calvin Klein (Algodón)",
    foto: "./img/ck.jpg",
    descripcion: "Docena de less CK de algodón, con elastico afelpado de 30mm. La docena viene surtida en 3 colores, negro, blanco y gris (4 unidades de cada color).",
    precio: 5600,
},
{
    id: 3,
    nombre: "Pink (Algodón)",
    foto: "./img/pink.jpeg",
    descripcion: "Docena de less Pink de algodón, con elastico afelpado de 30mm. La docena viene surtida en 3 colores, negro, blanco y gris (4 unidades de cada color).",
    precio: 5600,
},
{
    id: 4,
    nombre: "Tommy (Algodón)",
    foto: "./img/tommy.jpeg",
    descripcion: "Docena de less Tommy de algodón, con elastico afelpado de 30mm. La docena viene surtida en 3 colores, negro, blanco y gris (4 unidades de cada color).",
    precio: 5600,
},
{
    id: 5,
    nombre: "Pink (Puntilla)",
    foto: "./img/pinkpuntilla.jpeg",
    descripcion: "Docena de less Pink de puntilla, con elastico afelpado de 30mm. La docena viene surtida en 3 colores, negro, blanco y rojo (4 unidades de cada color).",
    precio: 6000,
},
{
    id: 6,
    nombre: "Victoria's Secret (Puntilla)",
    foto: "./img/vspunt.jpeg",
    descripcion: "Docena de less Victoria's Secret de puntilla, con elastico afelpado de 30mm. La docena viene surtida en 3 colores, negro, blanco y rojo (4 unidades de cada color).",
    precio: 6000,
},
]; 